import { Droplet, LifeBuoy, Truck, Wrench } from "lucide-react"

import type { Brand, Category, Product } from "./types"

export const categories: Category[] = [
  { id: "tyres", label: "Tyres", icon: LifeBuoy },
  { id: "lubricants", label: "Oil & Fluids", icon: Droplet },
  { id: "services", label: "Workshop Services", icon: Wrench },
  { id: "logistics", label: "Transport", icon: Truck },
]

export const brands: Brand[] = [
  { id: "michelin", label: "Michelin", categoryId: "tyres", icon: LifeBuoy },
  { id: "bridgestone", label: "Bridgestone", categoryId: "tyres", icon: LifeBuoy },
  { id: "pirelli", label: "Pirelli", categoryId: "tyres", icon: LifeBuoy },
  { id: "shell", label: "Shell", categoryId: "lubricants", icon: Droplet },
  { id: "mobil", label: "Mobil 1", categoryId: "lubricants", icon: Droplet },
  { id: "castrol", label: "Castrol", categoryId: "lubricants", icon: Droplet },
  { id: "rapidcare", label: "RapidCare", categoryId: "services", icon: Wrench },
  { id: "proline", label: "ProLine", categoryId: "services", icon: Wrench },
  { id: "diagnostic", label: "DiagWorks", categoryId: "services", icon: Wrench },
  { id: "cityhaul", label: "City Haul", categoryId: "logistics", icon: Truck },
  { id: "fleetback", label: "FleetBack", categoryId: "logistics", icon: Truck },
  { id: "lastmile", label: "Last Mile", categoryId: "logistics", icon: Truck },
]

export const products: Product[] = [
  {
    id: "pilot-sport-4",
    name: "Pilot Sport 4 (18\" 245/40)",
    price: 980,
    categoryId: "tyres",
    brandId: "michelin",
    brandName: "Michelin",
  },
  {
    id: "primacy-3",
    name: "Primacy 3 ST (17\" 225/55)",
    price: 820,
    categoryId: "tyres",
    brandId: "michelin",
    brandName: "Michelin",
  },
  {
    id: "battlax-t32",
    name: "Battlax T32 Motorcycle Tyre",
    price: 720,
    categoryId: "tyres",
    brandId: "bridgestone",
    brandName: "Bridgestone",
  },
  {
    id: "duravis-r660",
    name: "Duravis R660 Van Tyre",
    price: 640,
    categoryId: "tyres",
    brandId: "bridgestone",
    brandName: "Bridgestone",
  },
  {
    id: "p-zero",
    name: "P ZERO Performance Set",
    price: 1150,
    categoryId: "tyres",
    brandId: "pirelli",
    brandName: "Pirelli",
  },
  {
    id: "scorpion-atr",
    name: "Scorpion ATR SUV Tyre",
    price: 990,
    categoryId: "tyres",
    brandId: "pirelli",
    brandName: "Pirelli",
  },
  {
    id: "shell-helix-ultra",
    name: "Shell Helix Ultra 5W-40 (4L)",
    price: 265,
    categoryId: "lubricants",
    brandId: "shell",
    brandName: "Shell",
  },
  {
    id: "shell-atf",
    name: "Shell ATF 134 Transmission Fluid",
    price: 190,
    categoryId: "lubricants",
    brandId: "shell",
    brandName: "Shell",
  },
  {
    id: "mobil-esp",
    name: "Mobil 1 ESP 0W-20 (1L)",
    price: 110,
    categoryId: "lubricants",
    brandId: "mobil",
    brandName: "Mobil 1",
  },
  {
    id: "mobil-gear",
    name: "Mobil Gear Oil 75W-90",
    price: 175,
    categoryId: "lubricants",
    brandId: "mobil",
    brandName: "Mobil 1",
  },
  {
    id: "castrol-magnatec",
    name: "Castrol Magnatec 10W-40 (4L)",
    price: 210,
    categoryId: "lubricants",
    brandId: "castrol",
    brandName: "Castrol",
  },
  {
    id: "castrol-brake",
    name: "Castrol Brake Fluid DOT 4",
    price: 85,
    categoryId: "lubricants",
    brandId: "castrol",
    brandName: "Castrol",
  },
  {
    id: "rapidcare-service",
    name: "RapidCare Full Service Package",
    price: 580,
    categoryId: "services",
    brandId: "rapidcare",
    brandName: "RapidCare",
  },
  {
    id: "rapidcare-balance",
    name: "RapidCare Wheel Alignment + Balance",
    price: 220,
    categoryId: "services",
    brandId: "rapidcare",
    brandName: "RapidCare",
  },
  {
    id: "proline-aircon",
    name: "ProLine Air-Con Restoration",
    price: 360,
    categoryId: "services",
    brandId: "proline",
    brandName: "ProLine",
  },
  {
    id: "proline-detail",
    name: "ProLine Detailing & Coating",
    price: 740,
    categoryId: "services",
    brandId: "proline",
    brandName: "ProLine",
  },
  {
    id: "diagworks-diagnosis",
    name: "DiagWorks Computer Diagnostics",
    price: 180,
    categoryId: "services",
    brandId: "diagnostic",
    brandName: "DiagWorks",
  },
  {
    id: "diagworks-battery",
    name: "DiagWorks Battery Replacement",
    price: 420,
    categoryId: "services",
    brandId: "diagnostic",
    brandName: "DiagWorks",
  },
  {
    id: "cityhaul-flatbed",
    name: "City Haul Flatbed Return",
    price: 320,
    categoryId: "logistics",
    brandId: "cityhaul",
    brandName: "City Haul",
  },
  {
    id: "cityhaul-emergency",
    name: "City Haul Emergency Pickup",
    price: 450,
    categoryId: "logistics",
    brandId: "cityhaul",
    brandName: "City Haul",
  },
  {
    id: "fleetback-intercity",
    name: "FleetBack Intercity Delivery",
    price: 680,
    categoryId: "logistics",
    brandId: "fleetback",
    brandName: "FleetBack",
  },
  {
    id: "fleetback-storage",
    name: "FleetBack 3-Day Storage",
    price: 260,
    categoryId: "logistics",
    brandId: "fleetback",
    brandName: "FleetBack",
  },
  {
    id: "lastmile-doorstep",
    name: "Last Mile Doorstep Return",
    price: 210,
    categoryId: "logistics",
    brandId: "lastmile",
    brandName: "Last Mile",
  },
  {
    id: "lastmile-premium",
    name: "Last Mile Premium Shuttle",
    price: 380,
    categoryId: "logistics",
    brandId: "lastmile",
    brandName: "Last Mile",
  },
]
