import {
  Battery,
  CircleDot,
  Cog,
  Disc,
  LifeBuoy,
  Settings,
  Wrench,
} from "lucide-react"

import type { Brand, Category, Product } from "./types"

export const categories: Category[] = [
  { id: "tyre", label: "Tyre", icon: LifeBuoy },
  { id: "tube", label: "Tube", icon: CircleDot },
  { id: "flap", label: "Flap", icon: Disc },
  { id: "parts", label: "Parts", icon: Cog },
  { id: "rim", label: "Rim", icon: Settings },
  { id: "battery", label: "Battery", icon: Battery },
  { id: "services", label: "Services", icon: Wrench },
]

export const brands: Brand[] = [
  // Tyre brands
  { id: "roadx", label: "Road-X", categoryId: "tyre", icon: LifeBuoy },
  { id: "tercelo", label: "Tercelo", categoryId: "tyre", icon: LifeBuoy },
  { id: "mixedbrand", label: "Mixed Brand", categoryId: "tyre", icon: LifeBuoy },
  { id: "retread", label: "Retread", categoryId: "tyre", icon: LifeBuoy },
  { id: "continental", label: "Continental", categoryId: "tyre", icon: LifeBuoy },
  { id: "goodyear", label: "Goodyear", categoryId: "tyre", icon: LifeBuoy },
  { id: "opals", label: "Opals", categoryId: "tyre", icon: LifeBuoy },
  { id: "4x4", label: "4X4", categoryId: "tyre", icon: LifeBuoy },
  { id: "rimbaking", label: "Rimbaking", categoryId: "tyre", icon: LifeBuoy },
  // Tube brand
  { id: "tube", label: "Tube", categoryId: "tube", icon: CircleDot },
  // Flap brand
  { id: "flap", label: "Flap", categoryId: "flap", icon: Disc },
  // Parts brand
  { id: "parts", label: "Parts", categoryId: "parts", icon: Cog },
  // Rim brand
  { id: "rim", label: "Rim", categoryId: "rim", icon: Settings },
  // Battery brand
  { id: "battery", label: "Battery", categoryId: "battery", icon: Battery },
  // Services brand
  { id: "services", label: "Services", categoryId: "services", icon: Wrench },
]

export const products: Product[] = [
  // TUBE products
  { id: "TU-0001", name: "600X16(S) New Import Tube", price: 45, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0002", name: "8.3X22(S) New Import Tube", price: 52, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0003", name: "9.5X24 New Import Tube", price: 58, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0004", name: "12.4X24 New Import Tube", price: 65, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0005", name: "14.9X24 New Import Tube", price: 72, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0006", name: "16.9X24 New Import Tube", price: 78, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0007", name: "14X28 New Import Tube", price: 68, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0008", name: "520X12\" New Import Tube", price: 35, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0009", name: "520X13\" New Import Tube", price: 38, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0010", name: "640X14\" New Import Tube", price: 42, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0011", name: "670/700X15(S) New Import Tube", price: 48, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0012", name: "700/750X15(S) New Import Tube", price: 52, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0013", name: "670X15(L) New Import Tube", price: 50, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0014", name: "700/750X15(L) New Import Tube", price: 55, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0015", name: "700/750X16(S) New Import Tube", price: 58, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0016", name: "700/750X16(L) New Import Tube", price: 62, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0017", name: "900X16 New Import Tube", price: 75, categoryId: "tube", brandId: "tube", brandName: "Tube" },
  { id: "TU-0018", name: "900/1000X20 New Import Tube", price: 85, categoryId: "tube", brandId: "tube", brandName: "Tube" },

  // ROAD-X TYRE products
  { id: "RX-0001", name: "155/70R12 H01 RoadX Tyre", price: 145, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0002", name: "165/60R13 MX440 RoadX Tyre", price: 155, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0003", name: "175/70R13 MX440 RoadX Tyre", price: 165, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0004", name: "175R13 C02 RoadX Tyre", price: 175, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0005", name: "165/55R14 MX440 RoadX Tyre", price: 168, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0006", name: "175/65R14 MX440 RoadX Tyre", price: 178, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0007", name: "185/60R14 MX440 RoadX Tyre", price: 188, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0008", name: "185R14 C02 RoadX Tyre", price: 195, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0009", name: "185/55R15 MX440 RoadX Tyre", price: 205, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0010", name: "195/50R15 MX440 RoadX Tyre", price: 215, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0011", name: "195/55R15 H12 RoadX Tyre", price: 225, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0012", name: "195/60R15 H12 RoadX Tyre", price: 235, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0013", name: "195/65R15 MX440 RoadX Tyre", price: 245, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0014", name: "205/65R15 MX440 RoadX Tyre", price: 265, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0015", name: "205/70R15 MX440 RoadX Tyre", price: 275, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },
  { id: "RX-0016", name: "195R15 C02 RoadX Tyre", price: 255, categoryId: "tyre", brandId: "roadx", brandName: "Road-X" },

  // TERCELO TYRE products
  { id: "TC-0001", name: "175/70R13 PRO C6 Tercelo Tyre", price: 185, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0002", name: "175R13 WZT 705 Tercelo Tyre", price: 195, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0003", name: "175/65R14 PRO C6 Tercelo Tyre", price: 205, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0004", name: "185/70R14 PRO C6 Tercelo Tyre", price: 215, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0005", name: "195/70R14 PRO C6 Tercelo Tyre", price: 225, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0006", name: "165R14 WZT 705 Tercelo Tyre", price: 198, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0007", name: "185/60R15 PRO C6 Tercelo Tyre", price: 235, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0008", name: "195/50R15 PRO C6 Tercelo Tyre", price: 245, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0009", name: "185/55R15 PRO C6 Tercelo Tyre", price: 238, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0010", name: "185/55R16 PRO C6 Tercelo Tyre", price: 258, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0011", name: "195/55R15 SPORT D1 Tercelo Tyre", price: 268, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0012", name: "195/60R15 PRO C6 Tercelo Tyre", price: 255, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0013", name: "195/65R15 PRO C6 Tercelo Tyre", price: 265, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0014", name: "195/50R16 PRO C6 Tercelo Tyre", price: 275, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0015", name: "205/65R15 PRO C6 Tercelo Tyre", price: 285, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0016", name: "205/45R16 PRO C6 Tercelo Tyre", price: 295, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0017", name: "205/50R16 PRO C6 Tercelo Tyre", price: 305, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0018", name: "205/55R16 PRO C6 Tercelo Tyre", price: 315, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0019", name: "205/60R16 PRO C6 Tercelo Tyre", price: 325, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0020", name: "215/60R16 PRO C6 Tercelo Tyre", price: 345, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0021", name: "215/45R17 SPORT D1 Tercelo Tyre", price: 365, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },
  { id: "TC-0022", name: "215/55R17 SPORT D1 Tercelo Tyre", price: 375, categoryId: "tyre", brandId: "tercelo", brandName: "Tercelo" },

  // MIXED BRAND TYRE products
  { id: "AP-0001", name: "215/55R17 A610 Aplus Tyre", price: 345, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "BH-0001", name: "165/55R14 HH11 BlackHawk Tyre", price: 185, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "BH-0002", name: "175/60R15 HH1 BlackHawk Tyre", price: 205, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "BL-0001", name: "165/50R15 PO3 BlackArrow Tyre", price: 195, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "BL-0002", name: "165/60R13 PO9 BlackArrow Tyre", price: 165, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "BS-0001", name: "265/60R18 AT002 Bridgestone Tyre", price: 685, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "BS-0002", name: "215/75R17.5 R294 Bridgestone Tyre", price: 545, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "CN-0001", name: "11R22.5 China Tyre", price: 425, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "CN-0002", name: "295/80R22.5 China Tyre", price: 465, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DC-0001", name: "400X12 DRC Tyre", price: 125, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DM-0001", name: "155/70R12 AP203A Diamond Tyre", price: 145, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DN-0001", name: "700R16 Y203 Danacargo Tyre", price: 365, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DN-0002", name: "750R16 Y203 Danacargo Tyre", price: 395, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DN-0003", name: "215/75R17.5 Y203 Danacargo Tyre", price: 485, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DR-0001", name: "185/60R14 DP 200 Duringon Tyre", price: 195, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DR-0002", name: "185/65R15 DP 200 Duringon Tyre", price: 215, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DR-0003", name: "195/55R15 DP 200 Duringon Tyre", price: 235, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DS-0001", name: "175/65R14 DH 03 Double Star Tyre", price: 185, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DS-0002", name: "185/60R14 DH 03 Double Star Tyre", price: 195, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DS-0003", name: "195/55R15 DH 03 Double Star Tyre", price: 225, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "DT-0001", name: "SR203A Diastar Tyre", price: 155, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "GT-0001", name: "700X15 10PR Super 88N Giti Tyre", price: 285, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "GT-0002", name: "165R13 MAX MILEE PRO GT Radial Tyre", price: 175, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "KF-0001", name: "900X16 KingForest Tyre", price: 345, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "KH-0001", name: "185/55R15 PS31 KumHo Tyre", price: 285, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "KH-0002", name: "195/50R15 PS31 KumHo Tyre", price: 295, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "KH-0003", name: "195/55R15 PS31 KumHo Tyre", price: 305, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "KP-0001", name: "215/75R17.5 HS928 Kapsen Tyre", price: 465, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "KP-0002", name: "225/80R17.5 HS211 Kapsen Tyre", price: 495, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "KS-0001", name: "215/75R17.5 HS928 Kpsen Tyre", price: 455, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "KS-0002", name: "225/80R17.5 HS211 Kpsen Tyre", price: 485, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "MW-0001", name: "175/70R13 M1 Maxwind Tyre", price: 165, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "MX-0001", name: "225/80R17.5 MA265 Maxxis Tyre", price: 545, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "PL-0001", name: "185/60R15 CNT-Rosso Pirelli Tyre", price: 385, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "SN-0001", name: "205/65R15 EcoPro 99 Sonix Tyre", price: 265, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "SN-0002", name: "195/50R16 EcoPro 99 Sonix Tyre", price: 275, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "SW-0001", name: "750X15 12PR Swallow Tyre", price: 295, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "TY-0001", name: "195/50R16 PXR50 Toyo Tyre", price: 355, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },
  { id: "UT-0001", name: "Used Tyre", price: 85, categoryId: "tyre", brandId: "mixedbrand", brandName: "Mixed Brand" },

  // RETREAD TYRE products
  { id: "RT-0001", name: "670X15 (R) CXG Tyre", price: 165, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0002", name: "670X15 (R) TC Tyre", price: 155, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0003", name: "700X15 (R) CXG Tyre", price: 175, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0004", name: "700X15 (R) TC Tyre", price: 165, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0005", name: "750X15 (R) CXG Tyre", price: 185, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0006", name: "700X16 (R) CXG Tyre", price: 178, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0007", name: "700X16 (R) TC Tyre", price: 168, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0008", name: "700X16 (R) U118 Tyre", price: 172, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0009", name: "750X16 (R) CXG Tyre", price: 195, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0010", name: "900X16 (R) AT117 Tyre", price: 225, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0011", name: "1000X20 (PC/KT5) Tyre", price: 285, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0012", name: "225/80R17.5 Used Tyre", price: 145, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0013", name: "225/80R17.5 (PC) PCLL Tyre", price: 245, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0014", name: "10R22.5 Used Tyre", price: 165, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0015", name: "11R22.5 (PC/KT5) Tyre", price: 295, categoryId: "tyre", brandId: "retread", brandName: "Retread" },
  { id: "RT-0016", name: "295/80R22.5 (PC/KT5) Tyre", price: 315, categoryId: "tyre", brandId: "retread", brandName: "Retread" },

  // FLAP products
  { id: "FP-0001", name: "670/700/750X15 New Flap", price: 25, categoryId: "flap", brandId: "flap", brandName: "Flap" },
  { id: "FP-0002", name: "700/750X16 New Flap", price: 28, categoryId: "flap", brandId: "flap", brandName: "Flap" },
  { id: "FP-0003", name: "825/900//1000X20 New Flap", price: 35, categoryId: "flap", brandId: "flap", brandName: "Flap" },

  // PARTS products
  { id: "OT-0001", name: "Camber Nut (Small)", price: 12, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0002", name: "Camber Nut (Big)", price: 15, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0003", name: "Centre Corn", price: 8, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0004", name: "Tip-Top No. 1", price: 5, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0005", name: "Tip-Top No. 2", price: 6, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0006", name: "Tip-Top No. 3", price: 7, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0007", name: "Tip-Top No. 4", price: 8, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0008", name: "Tubeless Head (Rubber)", price: 10, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0009", name: "Tubeless Head (Steel) - Car", price: 15, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0010", name: "Tubeless Head (Steel) - Truck", price: 18, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0011", name: "Absober Moulting", price: 45, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0012", name: "Absober Links Myvi", price: 55, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0013", name: "Upper Arm", price: 125, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0014", name: "Lower Arm", price: 135, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0015", name: "Autobac Semi Synthetic", price: 85, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0016", name: "Autobac Fully Synthetic", price: 125, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0017", name: "295X80R22.5 (PC) Own Casing", price: 185, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0018", name: "11R22.5 (PC) Own Casing", price: 175, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0019", name: "Castrol 20-W40 Engine Oil", price: 95, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0020", name: "Oil Filter", price: 25, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0021", name: "Tip-Top CT 10", price: 12, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0022", name: "Tip-Top CT 12", price: 14, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0023", name: "Tip-Top CT 14", price: 16, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0024", name: "Tyre Bearing", price: 35, categoryId: "parts", brandId: "parts", brandName: "Parts" },
  { id: "OT-0025", name: "Other Parts", price: 20, categoryId: "parts", brandId: "parts", brandName: "Parts" },

  // CONTINENTAL TYRE products
  { id: "CT-0001", name: "175/65R14 CC7 Continental Tyre", price: 285, categoryId: "tyre", brandId: "continental", brandName: "Continental" },
  { id: "CT-0002", name: "185/60R15 CC7 Continental Tyre", price: 315, categoryId: "tyre", brandId: "continental", brandName: "Continental" },
  { id: "CT-0003", name: "185/65R15 CC7 Continental Tyre", price: 325, categoryId: "tyre", brandId: "continental", brandName: "Continental" },
  { id: "CT-0004", name: "195/55R15 CC7 Continental Tyre", price: 345, categoryId: "tyre", brandId: "continental", brandName: "Continental" },

  // RIM products
  { id: "RM-0001", name: "17.5 New Rim", price: 285, categoryId: "rim", brandId: "rim", brandName: "Rim" },
  { id: "RM-0002", name: "22.5 New Rim", price: 365, categoryId: "rim", brandId: "rim", brandName: "Rim" },

  // BATTERY products
  { id: "BA-0001", name: "N40ZL/44B19L (MF) ABM Battery", price: 185, categoryId: "battery", brandId: "battery", brandName: "Battery" },
  { id: "BA-0002", name: "NS60/NS60L/55B24RS/55B24RL Battery", price: 225, categoryId: "battery", brandId: "battery", brandName: "Battery" },
  { id: "BA-0003", name: "NS70/NS70L/80D26RS & 80D26RL Battery", price: 285, categoryId: "battery", brandId: "battery", brandName: "Battery" },
  { id: "BA-0004", name: "NX120-7/NX120-7L / 95D31R/95D31L Battery", price: 345, categoryId: "battery", brandId: "battery", brandName: "Battery" },
  { id: "BA-0005", name: "DIN66 (MF) ABM Battery", price: 295, categoryId: "battery", brandId: "battery", brandName: "Battery" },
  { id: "BA-0006", name: "N150 ABM Battery", price: 485, categoryId: "battery", brandId: "battery", brandName: "Battery" },
  { id: "BA-0007", name: "N120 ABM Battery", price: 425, categoryId: "battery", brandId: "battery", brandName: "Battery" },
  { id: "BA-0008", name: "N100 Century Battery", price: 385, categoryId: "battery", brandId: "battery", brandName: "Battery" },

  // SERVICES products
  { id: "SV-0001", name: "Alignment Services", price: 80, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0002", name: "Aligment (Front)", price: 50, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0003", name: "Aligment (Rear)", price: 50, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0004", name: "Aligment (Front & Rear)", price: 90, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0005", name: "Open Fixing", price: 20, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0006", name: "Balancing", price: 15, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0007", name: "Patching", price: 15, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0008", name: "Alignment Services & Open Fixing", price: 95, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0009", name: "Open Fixing & Balancing", price: 30, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0010", name: "Open Fixing & Patching", price: 30, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0011", name: "Fixing Tyre", price: 25, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0012", name: "Adjust Camber", price: 35, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0013", name: "Adjust Caster", price: 35, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0014", name: "Adjust Camber & Caster", price: 60, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0015", name: "Workmanship", price: 45, categoryId: "services", brandId: "services", brandName: "Services" },
  { id: "SV-0016", name: "Parts Services", price: 40, categoryId: "services", brandId: "services", brandName: "Services" },

  // GOODYEAR TYRE products
  { id: "GY-0001", name: "175/65R14 Assurance Duraplus 2 Goodyear Tyre", price: 295, categoryId: "tyre", brandId: "goodyear", brandName: "Goodyear" },
  { id: "GY-0002", name: "185/55R15 Assurance Maxguard Goodyear Tyre", price: 335, categoryId: "tyre", brandId: "goodyear", brandName: "Goodyear" },
  { id: "GY-0003", name: "195/55R15 Assurance Maxguard Goodyear Tyre", price: 355, categoryId: "tyre", brandId: "goodyear", brandName: "Goodyear" },
  { id: "GY-0004", name: "205/55R16 Assurance Maxguard Goodyear Tyre", price: 395, categoryId: "tyre", brandId: "goodyear", brandName: "Goodyear" },
  { id: "GY-0005", name: "700X16 G2020 Goodyear Tyre", price: 385, categoryId: "tyre", brandId: "goodyear", brandName: "Goodyear" },
  { id: "GY-0006", name: "700X16 CXG Goodyear Tyre", price: 375, categoryId: "tyre", brandId: "goodyear", brandName: "Goodyear" },
  { id: "GY-0007", name: "750X16 G2020 Goodyear Tyre", price: 425, categoryId: "tyre", brandId: "goodyear", brandName: "Goodyear" },
  { id: "GY-0008", name: "750X16 CXG Goodyear Tyre", price: 415, categoryId: "tyre", brandId: "goodyear", brandName: "Goodyear" },

  // OPALS TYRE products
  { id: "OP-0001", name: "195/50R16 FH666 Opals Tyre", price: 245, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0002", name: "195/60R16 FH666 Opals Tyre", price: 255, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0003", name: "195/65R15 FH888 Opals Tyre", price: 235, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0004", name: "205/50R16 FH888 Opals Tyre", price: 275, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0005", name: "205/55R16 FH888 Opals Tyre", price: 285, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0006", name: "205/45R17 FH888 Opals Tyre", price: 305, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0007", name: "215/45R17 FH888 Opals Tyre", price: 325, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0008", name: "215/50R17 FH888 Opals Tyre", price: 335, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0009", name: "215/55R17 FH888 Opals Tyre", price: 345, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0010", name: "215/60R16 FH666 Opals Tyre", price: 315, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0011", name: "215/55R18 FH18 Opals Tyre", price: 365, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0012", name: "215/60R17 FH18 Opals Tyre", price: 355, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0013", name: "225/60R18 FH18 Opals Tyre", price: 395, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0014", name: "225/65R17 FH18 Opals Tyre", price: 375, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0015", name: "225/45R18 FH888 Opals Tyre", price: 385, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0016", name: "225/55R19 FH18 Opals Tyre", price: 425, categoryId: "tyre", brandId: "opals", brandName: "Opals" },
  { id: "OP-0017", name: "235/50R18 FH18 Opals Tyre", price: 415, categoryId: "tyre", brandId: "opals", brandName: "Opals" },

  // 4X4 TYRE products
  { id: "44-0001", name: "31/10.5R15 MR-AT172 Mirage Tyre", price: 385, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0002", name: "31/10.5R15 RS23 Kapsen Tyre", price: 365, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0003", name: "31/10.5R15 A/T Tercelo Tyre", price: 375, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0004", name: "31/10.5R15 M/T Comforser Tyre", price: 395, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0005", name: "215/55R18 SPORT D1 Tercelo Tyre", price: 365, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0006", name: "215/60R17 WZD105 Transmate Tyre", price: 345, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0007", name: "225/70R17 A25 BlackArrow Tyre", price: 375, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0008", name: "225/55R19 L-ZEAL 56 Grenlander Tyre", price: 425, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0009", name: "245/70R16 A/T WZR505 Tercelo Tyre", price: 435, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0010", name: "245/70R16 A/T RS23 Kapsen Tyre", price: 415, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0011", name: "265/70R16 A/T WZR505 Tercelo Tyre", price: 465, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0012", name: "265/65R17 A/T WZR505 Tercelo Tyre", price: 485, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0013", name: "265/60R18 A/T RS23 Kapsen Tyre", price: 495, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },
  { id: "44-0014", name: "265/70R15 Maxclaw A/T Winrun Tyre", price: 385, categoryId: "tyre", brandId: "4x4", brandName: "4X4" },

  // RIMBAKING TYRE products
  { id: "RB-0001", name: "670X15 10PR AT88 Rimbaking Tyre", price: 245, categoryId: "tyre", brandId: "rimbaking", brandName: "Rimbaking" },
  { id: "RB-0002", name: "670X15 10PR AT66 Rimbaking Tyre", price: 235, categoryId: "tyre", brandId: "rimbaking", brandName: "Rimbaking" },
  { id: "RB-0003", name: "700X15 DH802 Rimbaking Tyre", price: 265, categoryId: "tyre", brandId: "rimbaking", brandName: "Rimbaking" },
  { id: "RB-0004", name: "700X16 DH802 Rimbaking Tyre", price: 275, categoryId: "tyre", brandId: "rimbaking", brandName: "Rimbaking" },
  { id: "RB-0005", name: "700X15 DH804 Rimbaking Tyre", price: 285, categoryId: "tyre", brandId: "rimbaking", brandName: "Rimbaking" },
  { id: "RB-0006", name: "700X16 DH804 Rimbaking Tyre", price: 295, categoryId: "tyre", brandId: "rimbaking", brandName: "Rimbaking" },
]
