import {
  CakeSlice,
  Coffee,
  CupSoda,
  IceCream,
  Pizza,
  Salad,
  Sandwich,
  Soup,
} from "lucide-react";

import type { Category, Product } from "./types";

export const categories: Category[] = [
  { id: "coffee", label: "Coffee", icon: Coffee },
  { id: "tea", label: "Tea & Infusions", icon: CupSoda },
  { id: "bakes", label: "Baked Goods", icon: CakeSlice },
  { id: "meals", label: "Hot Meals", icon: Soup },
  { id: "fresh", label: "Fresh Bites", icon: Salad },
  { id: "sandwiches", label: "Sandwiches", icon: Sandwich },
  { id: "treats", label: "Treats", icon: IceCream },
  { id: "pizza", label: "Flatbreads", icon: Pizza },
];

export const products: Product[] = [
  {
    id: "americano",
    name: "Americano",
    price: 3.5,
    categoryId: "coffee",
    description: "Double-shot espresso diluted with hot water.",
  },
  {
    id: "latte",
    name: "Vanilla Latte",
    price: 5.0,
    categoryId: "coffee",
    description: "Creamy latte with Madagascar vanilla.",
  },
  {
    id: "flat-white",
    name: "Flat White",
    price: 4.75,
    categoryId: "coffee",
    description: "Velvety espresso drink with silky milk.",
  },
  {
    id: "mocha",
    name: "Dark Mocha",
    price: 5.25,
    categoryId: "coffee",
    description: "Chocolate espresso drink topped with cocoa.",
  },
  {
    id: "chai",
    name: "Masala Chai",
    price: 4.25,
    categoryId: "tea",
    description: "Slow brewed spices, cardamom honey finish.",
  },
  {
    id: "matcha",
    name: "Iced Matcha",
    price: 4.9,
    categoryId: "tea",
    description: "Ceremonial grade matcha lightly sweetened.",
  },
  {
    id: "hibiscus",
    name: "Hibiscus Cooler",
    price: 4.5,
    categoryId: "tea",
    description: "Refreshing herbal iced infusion.",
  },
  {
    id: "peppermint",
    name: "Peppermint Tea",
    price: 3.75,
    categoryId: "tea",
    description: "Caffeine-free organic mint leaves.",
  },
  {
    id: "croissant",
    name: "Butter Croissant",
    price: 3.25,
    categoryId: "bakes",
    description: "Layers of French butter laminated daily.",
  },
  {
    id: "muffin",
    name: "Blueberry Muffin",
    price: 3.5,
    categoryId: "bakes",
    description: "Wild blueberries, lemon zest crumble top.",
  },
  {
    id: "bagel",
    name: "Everything Bagel",
    price: 2.75,
    categoryId: "bakes",
    description: "Served toasted with whipped cream cheese.",
  },
  {
    id: "quiche",
    name: "Spinach Quiche",
    price: 6.0,
    categoryId: "meals",
    description: "Flaky crust with spinach, feta, caramelized onions.",
  },
  {
    id: "soup",
    name: "Tomato Basil Soup",
    price: 5.75,
    categoryId: "meals",
    description: "Roasted tomatoes, garlic, basil oil finish.",
  },
  {
    id: "pasta",
    name: "Pesto Pasta",
    price: 8.5,
    categoryId: "meals",
    description: "Orecchiette tossed in kale-basil pesto.",
  },
  {
    id: "salad-bowl",
    name: "Harvest Salad",
    price: 9.0,
    categoryId: "fresh",
    description: "Greens, roasted squash, pepitas, cider vinaigrette.",
  },
  {
    id: "parfait",
    name: "Granola Parfait",
    price: 4.95,
    categoryId: "fresh",
    description: "Greek yogurt, citrus honey, seed granola.",
  },
  {
    id: "veggie-sandwich",
    name: "Veggie Sandwich",
    price: 8.0,
    categoryId: "sandwiches",
    description: "Grilled veggies, basil aioli, toasted focaccia.",
  },
  {
    id: "club-sandwich",
    name: "Smoky Club",
    price: 9.5,
    categoryId: "sandwiches",
    description: "Turkey, bacon jam, greens, sourdough.",
  },
  {
    id: "gelato",
    name: "Sea Salt Gelato",
    price: 4.4,
    categoryId: "treats",
    description: "Small batch caramel gelato.",
  },
  {
    id: "cookie",
    name: "Chocolate Chunk Cookie",
    price: 2.95,
    categoryId: "treats",
    description: "Browned butter dough, dark chocolate.",
  },
  {
    id: "margherita",
    name: "Margherita Flatbread",
    price: 10.0,
    categoryId: "pizza",
    description: "Fresh mozzarella, basil, charred tomatoes.",
  },
  {
    id: "truffle",
    name: "Truffle Mushroom Flatbread",
    price: 11.5,
    categoryId: "pizza",
    description: "Roasted mushrooms, fontina, truffle oil.",
  },
];
